spring:
  datasource:
    url: jdbc:mysql://192.168.91.139:3306/springbootdb?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: shine
